[project]
name = "network-automation"
version = "1.0.0"
authors = [
    { name = "Bogdan Radu" }
]
dependencies = [
    "mydict~=2.1.0"
    ]

[build-system]
requires = ["setuptools>=61.3"]
build-backend = "setuptools.build_meta"
